version: "3.8"

services:
  front-despacho:
    build: ./front_despacho
    container_name: tienda-front_despacho
    ports:
      - "8080:80"

  back-ventas:
    build: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: tienda-back-ventas
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin123

  back-despachos:
    build: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: tienda-back-despachos
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin123

  db:
    image: mysql:8
    container_name: tienda-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_despachos
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: